### ISSUE TITLE
On creation of new project, boot.lua fails to compile.

### ISSUE THREAD

**Issue by 4Dimensional** [crownengine/crown#93]

**Comment by douglaslassance** [comment]
I had this issue until I moved the engine folder from `C:\Program Files` to somewhere in my `%USERPROFILE%`.
Hope that helps.

**Comment by dbartolini** [comment]
This should fix it: https://github.com/crownengine/crown/commit/fc97e8d0d10fda81641a67949050aed4328a6f02
